version: '3.4'

services:
  productmicroservicewithdocker:
    image: ${DOCKER_REGISTRY-}productmicroservicewithdocker
    build:
      context: .
      dockerfile: ProductMicroServiceWithDocker\Dockerfile
